name: Test Timeout
on: push

jobs: 
    test-timeout:
        runs-on: ubuntu-latest
        
        steps:
            - name: Some Step
              run: sleep 200
              timeout-minutes: 0.5
